export default RouterNames = {
  HOME: 'Home',
  DRAWER_HOME: 'DrawerHome',
  BOTTOMTAB_HOME: 'BottomTabHome',
  PROFILE: 'Profile',
  CATEGORIES: 'Categories',
  CALENDAR: 'Calendar',
  CATEGORY: 'Category',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGOT_PASSWORD: 'ForgotPassword',
  SETTINGS: 'Settings',
  FAV_SERVICES: 'FavServices',
  ABOUT_US: 'AboutUs',
  PAST_APPTS: 'PastAppts',
  CONTACT: 'Contact',
  VIDEOS: 'Videos',
  SCHEDULE:'Schedule',
  NEW_APPOINTMENT:'NewAppointment'
};
